# Generated by Django 5.0.4 on 2025-11-23 05:57

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[accounts.models.validate_digits])),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[accounts.models.validate_digits])),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[accounts.models.validate_letters])),
                ('center_type', models.CharField(choices=[('NGO', 'NGO'), ('ORPHANAGE', 'ORPHANAGE'), ('SHELTER', 'SHELTER')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[accounts.models.validate_digits])),
                ('email', models.EmailField(max_length=254, validators=[accounts.models.validate_email_local_lower_letters])),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, validators=[accounts.models.validate_letters])),
                ('phone', models.CharField(max_length=15, validators=[accounts.models.validate_digits])),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='accounts.supportcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200, validators=[accounts.models.validate_letters])),
                ('donor_phone', models.CharField(max_length=15, validators=[accounts.models.validate_digits])),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.IntegerField(validators=[accounts.models.validate_non_negative_integer])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_to', to='accounts.supportcenter')),
                ('via_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_via', to='accounts.volunteer')),
            ],
        ),
    ]
