# Generated by Django 5.0.4 on 2025-11-23 15:53

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # ⚠️ AddField for donation.address, donation.donation_type, and donation.donor
        # have been removed because those columns already exist in the DB.


        migrations.AddField(
            model_name='supportcenter',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 23, 15, 52, 23, 88540, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportcenter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='available_time',
            field=models.CharField(
                max_length=100,
                blank=True,
                help_text='Example: Weekends 10am–2pm',
            ),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(blank=True),
        ),

        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(max_length=150, blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(max_length=20, blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='to_center',
            field=models.ForeignKey(
                to='accounts.supportcenter',
                related_name='donations',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name='donation',
            name='via_volunteer',
            field=models.ForeignKey(
                to='accounts.volunteer',
                related_name='donations',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='emergency_type',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('medical', 'Medical'),
                    ('fire', 'Fire'),
                    ('accident', 'Accident'),
                    ('natural_disaster', 'Natural Disaster'),
                    ('other', 'Other'),
                ],
                default='other',
            ),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='center_type',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('NGO', 'NGO'),
                    ('Orphanage', 'Orphanage'),
                    ('Shelter', 'Shelter'),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='user',
            field=models.OneToOneField(
                to=settings.AUTH_USER_MODEL,
                related_name='supportcenter',
                on_delete=django.db.models.deletion.CASCADE,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
