# Generated by Django 5.0.4 on 2026-02-27 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_assigned_center_volunteer_support_center_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='assigned_center',
            new_name='support_center',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supportcenter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supportcenter',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='supportcenter',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='assigned_at',
        ),
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('food', 'Food'), ('clothes', 'Clothes'), ('medicine', 'Medicine'), ('books', 'Books'), ('other', 'Other')], default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emergency',
            name='full_name',
            field=models.CharField(default='Unknown Person', max_length=150),
            preserve_default=False,
        ),
    ]
