# Generated by Django 5.0.4 on 2025-11-21 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_phone',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='to_center',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='via_volunteer',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='address',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='supportcenter',
            name='center_type',
        ),
        migrations.RemoveField(
            model_name='supportcenter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supportcenter',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='supportcenter',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='supportcenter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='full_name',
        ),
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='title',
            field=models.CharField(default='Donation', max_length=255),
        ),
        migrations.AddField(
            model_name='emergency',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='emergency',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emergency',
            name='name',
            field=models.CharField(default='Anonymous', max_length=120),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportcenter',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportcenter',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='emergency_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
