# Generated by Django 5.0.4 on 2025-11-21 17:32

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_donation_category_remove_donation_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='location',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supportcenter',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='supportcenter',
            name='lng',
        ),
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(default=0, validators=[accounts.models.validate_non_negative_integer]),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, default='Unknown', max_length=200, validators=[accounts.models.validate_letters]),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, default='0000000000', max_length=15, validators=[accounts.models.validate_digits]),
        ),
        migrations.AddField(
            model_name='donation',
            name='item',
            field=models.CharField(blank=True, default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='to_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_to', to='accounts.supportcenter'),
        ),
        migrations.AddField(
            model_name='donation',
            name='via_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_via', to='accounts.volunteer'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='address',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='emergency',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emergency',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supportcenter',
            name='center_type',
            field=models.CharField(blank=True, choices=[('NGO', 'NGO'), ('ORPHANAGE', 'ORPHANAGE'), ('SHELTER', 'SHELTER')], default='NGO', max_length=20),
        ),
        migrations.AddField(
            model_name='supportcenter',
            name='email',
            field=models.EmailField(blank=True, default='admin@example.com', max_length=254, validators=[accounts.models.validate_email_local_lower_letters]),
        ),
        migrations.AddField(
            model_name='supportcenter',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supportcenter',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supportcenter',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='full_name',
            field=models.CharField(blank=True, default='Unknown', max_length=200, validators=[accounts.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='emergency_type',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=15, validators=[accounts.models.validate_digits]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=15, validators=[accounts.models.validate_digits]),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=200, validators=[accounts.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='supportcenter',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=15, validators=[accounts.models.validate_digits]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='assigned_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='accounts.supportcenter'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=15, validators=[accounts.models.validate_digits]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
